platform :ios, ‘8.0’

target 'TravellerDiary' do
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~>3.8'
pod 'Masonry'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TravellerDiary

end
